### ISSUE TITLE
Inpainting not using --receptor_chain argument

### ISSUE THREAD

**Issue by ajbordner** [RosettaCommons/RFDesign#16]
Inpainting appears to be ignoring the --receptor_chain argument. The receptor chain is not included in the output PDB or .trb files.
Here is an example of designing a 20-residue loop in a heterodimer complex:

python RFDesign/inpainting/inpaint.py --pdb ~/structures/4i0c.pdb --contigs D1-95,20,D116-127 --out ~/output/4i0c_inpainting --receptor_chain A --dump_all

**Comment by joewatchwell** [comment]
Hi! Thanks for raising this, you're right that the --receptor_chain flag wasn't implemented. I've removed reference to it in the arguments, and explained in the README how to input a receptor chain (lines 87-94). 
Good luck!
Joe
