### ISSUE TITLE
Workflow for resultant inpainting models

### ISSUE THREAD

**Issue by jadolfbr** [RosettaCommons/RFDesign#30]
I think this code should maybe have a wiki attached to it to add general knowledge?
I have been able to run and get at least something out.  The PDBs do not inlclude rotamers/sidechains, but do include the identity of the residues.  What is your general workflow for then incorporating these sequences and modeling the side chains?  Do you have scripts available that you could share that does this?

**Comment by jueseph** [comment]
Hi Jared,

Sorry this isn't easier to use. Partly we are trying to put together newer
versions of the software to release that are more powerful, and so figured
we'd support those more seriously when they're released.

For this version of hallucination/inpainting, we use the trfold_relax.sh
script (see https://github.com/RosettaCommons/RFDesign/tree/main/scripts)
to add sidechains (using Rosetta).

I assumed Github issues would provide a forum for people to share notes on
how to run things. Wiki is a good idea too. Do you have a suggested
software/service that would plug in to Github?

Jue

**Comment by jadolfbr** [comment]
Hey Joe,

I think for a repo, you can select to have a wiki and it will be handled by Github.  I think it's a repo option in the settings.  It's really useful. There are some docs to it. https://carldesouza.com/creating-a-github-wiki-documentation-for-your-repository/

I did find the TRRosetta relax script and also realized if I just read and then dump a PDB in PyRosetta it will add side chains and pack them to the CB.  I think this information is just missing from the inpainting docs, but the relax script is in the hallucination docs.
