### ISSUE TITLE
no alphafold module in hallucination/models/

### ISSUE THREAD

**Issue by Sigurd-git** [RosettaCommons/RFDesign#5]
The af2_metrics.py requests a module called alphafold in hallucination/models/, but actually there is not such a module. I've copied [ ](https://github.com/deepmind/alphafold/tree/main/alphafold) to hallucination/models/, but there are still some compatible problems(maybe Deepmind updated their work?). Could you please push this module to your repository?

**Comment by Sigurd-git** [comment]
problems:
1. alphafold.data.pipeline.make_msa_features only require msas: Sequence[parsers.Msa], but af2_metrics.py transfer wrong msas(a string in a nested list) and a deletion_matrices which is not required by make_msa_features.
2. alphafold.common.protein.Protein requires a parameter called chain_index, but af2_metrics 316~321 line does not pass such a parameter. I'm not sure whether I can assign chain_index = np.zeros_like(residue_index), although it works.

I think the best solution is that you push the alphafold module of your version to your repository.

**Comment by Sigurd-git** [comment]
Sorry for my disturbance. After '''git checkout 00c4c91dcc4e43be2d7f02f998940f8a3a3bc0de''' in the repository of alphafold and copy the alphafold module of this version to RFDesign/hallucination/models/, the 2 problems above can be both fixed.

**Comment by jueseph** [comment]
Thanks for posting the info on this. We'll clean up the folder tree a
little so this doesn't have to be done manually in the future.
