### ISSUE TITLE
error while running Rifdock protocol

### ISSUE THREAD

**Issue by anneday** [RosettaCommons/RFDesign#57]
When I ran Step 12 in Cao protocol for binder design,  I prepared paper_interface_design_pilot_commands. List when I did RIFdocking step 12 Running a pilot job. But when I ran commands in the list, Dalphaball reports error below:
protocols.rosetta_scripts.ParsedProtocol: =======================BEGIN METRIC sap_score=======================
basic.io.database: Database file opened: scoring/score_functions/sap_sasa_calib.dat
WARNING!! DALPHABALL output nan at index 140724834832176
DALPHABALL output indicies not matching! 1!=140724834832176

ERROR:: Exit from: src/core/scoring/packing/surf_vol.cc line: 170
protocols.rosetta_scripts.ParsedProtocol: [ ERROR ] Exception while processing procotol:

File: src/core/scoring/packing/surf_vol.cc:170
[ ERROR ] UtilityExitException
ERROR:

protocols.jd2.JobDistributor: [ ERROR ]

[ERROR] Exception caught by JobDistributor for job ferr_hh_00251_000000134_0001

[ ERROR ]: Caught exception:

File: src/core/scoring/packing/surf_vol.cc:170
[ ERROR ] UtilityExitException
ERROR:

AN INTERNAL ERROR HAS OCCURED. PLEASE SEE THE CONTENTS OF ROSETTA_CRASH.log FOR DETAILS.

protocols.jd2.JobDistributor: [ WARNING ] ferr_hh_00251_000000134_0001 reported failure and will NOT retry
protocols.jd2.JobDistributor: no more batches to process...
protocols.jd2.JobDistributor: 20 jobs considered, 20 jobs attempted in 6349 seconds.
It seems that the error is caused by Dalphaball. 
And when I compiled Dalphaball in rosetta 3.13 with gcc 11.04:
gcc -o ./DAlphaBall.gcc -O3 DAlphaBall.o sos_minor_gmp.o alf_tools_gmp.o binding.o adjust.o alfcx.o alfcx_tools.o cavballs.o delcx.o truncate_real.o measure_tools.o surface_tools.o surface_only.o surface_deriv_coord.o volume_tools.o volume_only.o volume_deriv_coord.o vector.o write_simplices.o -L/usr/local/lib -lgmp  -lm -lgfortran
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1e85be0): multiple definition of `coord_gmp'; sos_minor_gmp.o:(.bss+0x1e85be0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xb80): multiple definition of `a_mp'; sos_minor_gmp.o:(.bss+0xb80): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xb20): multiple definition of `b_mp'; sos_minor_gmp.o:(.bss+0xb20): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xac0): multiple definition of `c_mp'; sos_minor_gmp.o:(.bss+0xac0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x13e0): multiple definition of `weight_gmp'; sos_minor_gmp.o:(.bss+0x13e0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1280): multiple definition of `temp1'; sos_minor_gmp.o:(.bss+0x1280): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1270): multiple definition of `temp2'; sos_minor_gmp.o:(.bss+0x1270): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x480): multiple definition of `Mab'; sos_minor_gmp.o:(.bss+0x480): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x340): multiple definition of `Mac'; sos_minor_gmp.o:(.bss+0x340): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x200): multiple definition of `Mbc'; sos_minor_gmp.o:(.bss+0x200): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xc0): multiple definition of `S'; sos_minor_gmp.o:(.bss+0xc0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x0): multiple definition of `T'; sos_minor_gmp.o:(.bss+0x0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xf30): multiple definition of `Dabc'; sos_minor_gmp.o:(.bss+0xf30): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x980): multiple definition of `Dab'; sos_minor_gmp.o:(.bss+0x980): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x9e0): multiple definition of `Sab'; sos_minor_gmp.o:(.bss+0x9e0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xa20): multiple definition of `Tab'; sos_minor_gmp.o:(.bss+0xa20): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xa60): multiple definition of `d_mp'; sos_minor_gmp.o:(.bss+0xa60): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xee0): multiple definition of `wa'; sos_minor_gmp.o:(.bss+0xee0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xed0): multiple definition of `wb'; sos_minor_gmp.o:(.bss+0xed0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xec0): multiple definition of `wc'; sos_minor_gmp.o:(.bss+0xec0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xeb0): multiple definition of `wd'; sos_minor_gmp.o:(.bss+0xeb0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xf437e0): multiple definition of `radius_gmp'; sos_minor_gmp.o:(.bss+0xf437e0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xea0): multiple definition of `ra_mp'; sos_minor_gmp.o:(.bss+0xea0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xe90): multiple definition of `rb_mp'; sos_minor_gmp.o:(.bss+0xe90): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xe80): multiple definition of `rc_mp'; sos_minor_gmp.o:(.bss+0xe80): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xe70): multiple definition of `rd_mp'; sos_minor_gmp.o:(.bss+0xe70): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xe60): multiple definition of `alp'; sos_minor_gmp.o:(.bss+0xe60): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x940): multiple definition of `Sac'; sos_minor_gmp.o:(.bss+0x940): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x900): multiple definition of `Sad'; sos_minor_gmp.o:(.bss+0x900): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x8c0): multiple definition of `Sbc'; sos_minor_gmp.o:(.bss+0x8c0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x880): multiple definition of `Sbd'; sos_minor_gmp.o:(.bss+0x880): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x840): multiple definition of `Scd'; sos_minor_gmp.o:(.bss+0x840): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1260): multiple definition of `temp3'; sos_minor_gmp.o:(.bss+0x1260): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x800): multiple definition of `Sa'; sos_minor_gmp.o:(.bss+0x800): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x7c0): multiple definition of `Sb'; sos_minor_gmp.o:(.bss+0x7c0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x5c0): multiple definition of `Sc'; sos_minor_gmp.o:(.bss+0x5c0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x780): multiple definition of `Sd'; sos_minor_gmp.o:(.bss+0x780): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x640): multiple definition of `Deter'; sos_minor_gmp.o:(.bss+0x640): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x740): multiple definition of `Sam1'; sos_minor_gmp.o:(.bss+0x740): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x700): multiple definition of `Sbm1'; sos_minor_gmp.o:(.bss+0x700): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x6c0): multiple definition of `Scm1'; sos_minor_gmp.o:(.bss+0x6c0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x680): multiple definition of `Sdm1'; sos_minor_gmp.o:(.bss+0x680): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xf70): multiple definition of `det1'; sos_minor_gmp.o:(.bss+0xf70): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xf60): multiple definition of `det2'; sos_minor_gmp.o:(.bss+0xf60): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xf40): multiple definition of `det4'; sos_minor_gmp.o:(.bss+0xf40): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xf50): multiple definition of `det3'; sos_minor_gmp.o:(.bss+0xf50): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xf20): multiple definition of `Dabd'; sos_minor_gmp.o:(.bss+0xf20): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xf10): multiple definition of `Dacd'; sos_minor_gmp.o:(.bss+0xf10): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xf00): multiple definition of `Dbcd'; sos_minor_gmp.o:(.bss+0xf00): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xef0): multiple definition of `Dabcd'; sos_minor_gmp.o:(.bss+0xef0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1000): multiple definition of `den'; sos_minor_gmp.o:(.bss+0x1000): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1010): multiple definition of `num'; sos_minor_gmp.o:(.bss+0x1010): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1030): multiple definition of `dist2'; sos_minor_gmp.o:(.bss+0x1030): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1040): multiple definition of `rb2'; sos_minor_gmp.o:(.bss+0x1040): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1050): multiple definition of `ra2'; sos_minor_gmp.o:(.bss+0x1050): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1020): multiple definition of `dtest'; sos_minor_gmp.o:(.bss+0x1020): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x600): multiple definition of `Tc'; sos_minor_gmp.o:(.bss+0x600): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xbe0): multiple definition of `res2_c'; sos_minor_gmp.o:(.bss+0xbe0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xd20): multiple definition of `res'; sos_minor_gmp.o:(.bss+0xd20): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xff0): multiple definition of `r_11'; sos_minor_gmp.o:(.bss+0xff0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xfe0): multiple definition of `r_22'; sos_minor_gmp.o:(.bss+0xfe0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xfd0): multiple definition of `r_33'; sos_minor_gmp.o:(.bss+0xfd0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xf90): multiple definition of `diff'; sos_minor_gmp.o:(.bss+0xf90): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xf80): multiple definition of `det0'; sos_minor_gmp.o:(.bss+0xf80): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xfc0): multiple definition of `r_14'; sos_minor_gmp.o:(.bss+0xfc0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xfb0): multiple definition of `r_313'; sos_minor_gmp.o:(.bss+0xfb0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0xfa0): multiple definition of `r_212'; sos_minor_gmp.o:(.bss+0xfa0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1060): multiple definition of `g3'; sos_minor_gmp.o:(.bss+0x1060): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1070): multiple definition of `g2'; sos_minor_gmp.o:(.bss+0x1070): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1080): multiple definition of `g1'; sos_minor_gmp.o:(.bss+0x1080): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1090): multiple definition of `f3'; sos_minor_gmp.o:(.bss+0x1090): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x10a0): multiple definition of `f2'; sos_minor_gmp.o:(.bss+0x10a0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x10b0): multiple definition of `f1'; sos_minor_gmp.o:(.bss+0x10b0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x10c0): multiple definition of `e3'; sos_minor_gmp.o:(.bss+0x10c0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x10d0): multiple definition of `e2'; sos_minor_gmp.o:(.bss+0x10d0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x10e0): multiple definition of `e1'; sos_minor_gmp.o:(.bss+0x10e0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x10f0): multiple definition of `d3'; sos_minor_gmp.o:(.bss+0x10f0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1100): multiple definition of `d2'; sos_minor_gmp.o:(.bss+0x1100): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1110): multiple definition of `d1'; sos_minor_gmp.o:(.bss+0x1110): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1120): multiple definition of `c44'; sos_minor_gmp.o:(.bss+0x1120): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1130): multiple definition of `c43'; sos_minor_gmp.o:(.bss+0x1130): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1140): multiple definition of `c42'; sos_minor_gmp.o:(.bss+0x1140): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1150): multiple definition of `c41'; sos_minor_gmp.o:(.bss+0x1150): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1160): multiple definition of `c34'; sos_minor_gmp.o:(.bss+0x1160): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1170): multiple definition of `c33'; sos_minor_gmp.o:(.bss+0x1170): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1180): multiple definition of `c32'; sos_minor_gmp.o:(.bss+0x1180): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1190): multiple definition of `c31'; sos_minor_gmp.o:(.bss+0x1190): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x11a0): multiple definition of `c24'; sos_minor_gmp.o:(.bss+0x11a0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x11b0): multiple definition of `c23'; sos_minor_gmp.o:(.bss+0x11b0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x11c0): multiple definition of `c22'; sos_minor_gmp.o:(.bss+0x11c0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x11d0): multiple definition of `c21'; sos_minor_gmp.o:(.bss+0x11d0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x11e0): multiple definition of `c14'; sos_minor_gmp.o:(.bss+0x11e0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x11f0): multiple definition of `c13'; sos_minor_gmp.o:(.bss+0x11f0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1200): multiple definition of `c12'; sos_minor_gmp.o:(.bss+0x1200): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1210): multiple definition of `c11'; sos_minor_gmp.o:(.bss+0x1210): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1220): multiple definition of `val3'; sos_minor_gmp.o:(.bss+0x1220): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1230): multiple definition of `val2'; sos_minor_gmp.o:(.bss+0x1230): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1240): multiple definition of `val1'; sos_minor_gmp.o:(.bss+0x1240): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1250): multiple definition of `temp4'; sos_minor_gmp.o:(.bss+0x1250): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1290): multiple definition of `a54_mp'; sos_minor_gmp.o:(.bss+0x1290): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x12a0): multiple definition of `a53_mp'; sos_minor_gmp.o:(.bss+0x12a0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x12b0): multiple definition of `a52_mp'; sos_minor_gmp.o:(.bss+0x12b0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x12c0): multiple definition of `a51_mp'; sos_minor_gmp.o:(.bss+0x12c0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x12d0): multiple definition of `a44_mp'; sos_minor_gmp.o:(.bss+0x12d0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x12e0): multiple definition of `a43_mp'; sos_minor_gmp.o:(.bss+0x12e0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x12f0): multiple definition of `a42_mp'; sos_minor_gmp.o:(.bss+0x12f0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1300): multiple definition of `a41_mp'; sos_minor_gmp.o:(.bss+0x1300): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1310): multiple definition of `a34_mp'; sos_minor_gmp.o:(.bss+0x1310): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1320): multiple definition of `a33_mp'; sos_minor_gmp.o:(.bss+0x1320): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1330): multiple definition of `a32_mp'; sos_minor_gmp.o:(.bss+0x1330): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1340): multiple definition of `a31_mp'; sos_minor_gmp.o:(.bss+0x1340): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1350): multiple definition of `a24_mp'; sos_minor_gmp.o:(.bss+0x1350): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1360): multiple definition of `a23_mp'; sos_minor_gmp.o:(.bss+0x1360): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1370): multiple definition of `a22_mp'; sos_minor_gmp.o:(.bss+0x1370): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1380): multiple definition of `a21_mp'; sos_minor_gmp.o:(.bss+0x1380): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x1390): multiple definition of `a14_mp'; sos_minor_gmp.o:(.bss+0x1390): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x13a0): multiple definition of `a13_mp'; sos_minor_gmp.o:(.bss+0x13a0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x13b0): multiple definition of `a12_mp'; sos_minor_gmp.o:(.bss+0x13b0): first defined here
/usr/bin/ld: alf_tools_gmp.o:(.bss+0x13c0): multiple definition of `a11_mp'; sos_minor_gmp.o:(.bss+0x13c0): first defined here
Could anyone tell me how to solve this?Please!
Thank you so much!

**Comment by roccomoretti** [comment]
This sounds like a similar issue to the one posted [on the RosettaCommons Forums](https://www.rosettacommons.org/node/11856). -- In summary, you need to use an earlier GCC version (like ~6.3) to compile Dalphaball. Also, you should double-check the settings of your -dalphaball option to make sure you're pointing to the proper Dalphaball executable.

At any rate, your issues here are unrelated to the RFDesign application proper, so if you have further questions about this issue, I'd encourage you to post at the RosettaCommons Forums.
