### ISSUE TITLE
Garbled output for inpainting

### ISSUE THREAD

**Issue by jadolfbr** [RosettaCommons/RFDesign#6]
Hello!

I am trying the inpainting test PDB.  When I try the default mask or another loop, I get a garbled PDB output. I realize it's backbone-only, but it has not structure, just looks like spaghetti.  Any recommendations? 

```
python ../inpaint.py --task hal --checkpoint v02 --pdb=input/2KL8.pdb --out=output/inpaint_test --window=A,20,25 --num_designs 1 --inf_method=multi_shot --n_iters 10 --recycle_str_mode both  --clamp_1d 0.1 --dump_all
```

**Comment by jadolfbr** [comment]
Also, I did try the workaround and copied the hallucination/cache directory to the working directory, but I still get the same output. 

<img width="477" alt="Screen Shot 2022-03-15 at 12 20 22 PM" src="https://user-images.githubusercontent.com/3290052/158423919-c605e7b3-b956-4da0-b520-6bb792d5122b.png">

**Comment by jueseph** [comment]
Hi, sorry for the late reply. This is likely an environment issue but it's
been very inconsistent so has been hard to pin down.

We're actually about to release a newer version of the code & weights. I'll
try to fix this as part of that update. I can let you know when we've done
that.

**Comment by jueseph** [comment]
I've updated the repo with newer versions of the code and underlying weights. There could still be problems as some of the dependencies are sensitive to exact versions (dgl, torch-geometric, etc). Give it a try and let me know if it works.

**Comment by jadolfbr** [comment]
Sounds great!  Will try it out!

**Comment by jadolfbr** [comment]
I am now on different hardware, and using the newer code allowed the tests to run to completion without garbled output.
